[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
relative_files = true

[tool.poetry]
name = "django-timezone-field"
version = "5.0"
description = "A Django app providing database and form fields for pytz timezone objects."
authors = ["Mike Fogel <mike@fogel.ca>"]
packages = [
    { include = "timezone_field" },
]

[tool.poetry.dependencies]
python = "^3.7"
pytz = "*"

[tool.poetry.dev-dependencies]
coverage = {extras = ["toml"], version = "^6.2"}
Django = "^3.2"
djangorestframework = "^3.13.1"
flake8 = "^4.0.1"
psycopg2-binary = "^2.9.3"
pytest = "^6.2.5"
pytest-django = "^4.5.2"
pytest-pythonpath = "^0.7.3"
pytest-lazy-fixture = "^0.6.3"
pytest-cov = "^3.0.0"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"
