name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install tox tox-gh-actions

    - name: Test with tox
      run: tox
      env:
        PLATFORM: ${{ matrix.platform }}
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

    - name: Upload to coveralls
      uses: AndreMiras/coveralls-python-action@v20201129
      with:
        parallel: true
        flag-name: Python ${{ matrix.python-version }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Finish coveralls
      uses: AndreMiras/coveralls-python-action@v20201129
      with:
        parallel-finished: true
